package server

import (
	"net/http"

	"Meme_Api/api/gimme"
	_ "Meme_Api/docs" // registers the swag-generated OpenAPI spec
	"Meme_Api/server/middleware"

	"github.com/gin-contrib/cors"
	"github.com/gin-gonic/gin"
	"github.com/swaggest/swgui"
	"github.com/swaggest/swgui/v5emb"
	"github.com/swaggo/swag"
)

// NewRouter : Function with routes
func NewRouter() *gin.Engine {
	gin.SetMode(gin.ReleaseMode)
	router := gin.New()

	// Gin and CORS Middlewares
	router.Use(gin.Logger())
	router.Use(gin.Recovery())
	router.Use(cors.Default())
	router.Use(middleware.RequestID())
	router.Use(middleware.RateLimit())

	// Health check
	router.GET("/healthz", func(c *gin.Context) {
		c.JSON(http.StatusOK, gin.H{"status": "ok"})
	})

	// Swagger UI (Swagger UI v5, assets embedded via swgui/v5emb, no CDN)
	router.GET("/", func(c *gin.Context) {
		c.Redirect(http.StatusMovedPermanently, "/swagger/")
	})
	// Serve the OpenAPI spec generated by swag from handler annotations.
	// Kept outside /swagger/ to avoid a gin route conflict with the catch-all below.
	router.GET("/openapi.json", func(c *gin.Context) {
		doc, err := swag.ReadDoc()
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "openapi spec unavailable"})
			return
		}
		c.Header("Content-Type", "application/json")
		c.String(http.StatusOK, doc)
	})
	// ShowTopBar renders Swagger UI's top bar, which holds the v5 dark-mode
	// toggle (Swagger UI >=5.31). It also exposes the spec URL explorer input.
	swaggerUI := v5emb.NewWithConfig(swgui.Config{ShowTopBar: true})
	router.GET("/swagger/*any", gin.WrapH(
		swaggerUI("Meme API", "/openapi.json", "/swagger/"),
	))

	// /gimme routes
	gimmeRouter := router.Group("gimme")
	gimme.Routes(gimmeRouter)

	return router
}
